# -*- coding: utf-8 -*-
"""14_JAN_2021.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rnL9bibo0fs8r5BQqX1LztR-jmXidcQE
"""

import pandas as pd

iris_data = pd.read_csv("irisdata.csv")

# print(iris_data)
# a = iris_data.dropna(inplace = True) #to remove null data

b = iris_data['sepal_length'].loc[131:135]
print(iris_data.to_string())

iris_data.fillna(12, inplace=True)
print(iris_data.to_string())
print(b)

print(iris_data)
c = iris_data.drop(["petal_width","species"],axis= 1)
print(c)
drop_row = iris_data.drop([0,1],axis =0)
print(drop_row)
